### ISSUE TITLE
Prestashop 1.7.7.x

### ISSUE THREAD

**Issue by a-suez** [shipit-team/prestashop#3]
No funciona con Prestashop 1.7.7.x, probé en 1.7.7.2 y en Frontend funciona perfecto, pero en backend arroja errores en la order page.

(adjunto log de errores al abrir el order page):

`ClassNotFoundException
HTTP 500 Internal Server Error
Attempted to load class "SubmitBulkAction" from the global namespace.
Did you forget a "use" statement for
"PrestaShop\PrestaShop\Core\Grid\Action\Bulk\Type\SubmitBulkAction"?
Exception Logs 2 Stack Trace
Internal Server Error
Symfony\Component\Debug\Exception\
ClassNotFoundException
1087. return array('street' => $street, 'number' => $number, 'numberAddition' => $numberAddition);
1088. }
1089.
1090. public function hookActionOrderGridDefinitionModifier($params) {
1091. $params['definition']->getBulkActions()->add(
1092. (new SubmitBulkAction('disable_selection'))
1093. ->setName('Subscribe newsletter')
1094. ->setOptions([
1095. 'submit_route' => 'admin_shipit_customers_bulk_subscribe_newsletter',
1096. ])
1097. );
in modules/rg_shipit/rg_shipit.php (line 1092)
Rg_Shipit -> hookActionOrderGridDefinitionModifier (array('_ps_version' => '1.7.7.2', 'request' => object(Request), 'route' => 'admin_orders_index',
'definition' => object(GridDefinition), 'cookie' => object(Cookie), 'cart' => null, 'altern' => 1))
in classes/Hook.php (line 990)
HookCore :: coreCallHook (object(Rg_Shipit), 'hookActionOrderGridDefinitionModifier', array('_ps_version' => '1.7.7.2', 'request' => object(Request), 'route'
=> 'admin_orders_index', 'definition' => object(GridDefinition), 'cookie' => object(Cookie), 'cart' => null, 'altern' => 1))
in classes/Hook.php (line 414)
HookCore :: callHookOn (object(Rg_Shipit), 'actionOrderGridDefinitionModifier', array('_ps_version' => '1.7.7.2', 'request' => object(Request), 'route' =>
'admin_orders_index', 'definition' => object(GridDefinition), 'cookie' => object(Cookie), 'cart' => null, 'altern' => 1))
in classes/Hook.php (line 927)
HookCore :: exec ('actionOrderGridDefinitionModifier', array('_ps_version' => '1.7.7.2', 'request' => object(Request), 'route' => 'admin_orders_index',
'definition' => object(GridDefinition), 'cookie' => object(Cookie), 'cart' => null, 'altern' => 1), 65, false)
in src/Adapter/LegacyHookSubscriber.php (line 292)
LegacyHookSubscriber -> __call ('call_445_65', array(object(HookEvent), 'actionOrderGridDefinitionModifier', null))
in src/Adapter/Hook/HookDispatcher.php (line 120)
HookDispatcher -> doDispatch (array(array(object(LegacyHookSubscriber), 'call_445_65')), 'actionOrderGridDefinitionModifier', object(HookEvent))
in src/Adapter/Hook/HookDispatcher.php (line 75)
HookDispatcher -> dispatch ('actionOrderGridDefinitionModifier', object(HookEvent))
in src/Adapter/Hook/HookDispatcher.php (line 156)
HookDispatcher -> dispatchForParameters ('actionOrderGridDefinitionModifier', array('definition' => object(GridDefinition)))
in src/Core/Hook/HookDispatcher.php (line 58)
HookDispatcher -> dispatchHook (object(Hook))
in src/Core/Hook/HookDispatcher.php (line 67)
HookDispatcher -> dispatchWithParameters ('actionOrderGridDefinitionModifier', array('definition' => object(GridDefinition)))
in src/Core/Grid/Definition/Factory/AbstractGridDefinitionFactory.php (line 94)
AbstractGridDefinitionFactory -> getDefinition ()
in src/Core/Grid/GridFactory.php (line 89)
GridFactory -> getGrid (object(OrderFilters))
in src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php (line 141)
OrderController -> indexAction (object(Request), object(OrderFilters))
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php (line 151)
HttpKernel -> handleRaw (object(Request), 1)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php (line 68)
HttpKernel -> handle (object(Request), 1, false)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php (line 200)
Kernel -> handle (object(Request), 1, false)
in admin123/index.php (line 82)`

Gracias por el desarrollo del plugin! Lo estábamos esperando :)!

Saludos

**Comment by sergioaraos** [comment]
Gracias por este aporte!  En la versión 1.7.7.3 con el plugin 1.2.3 

`public function hookActionOrderGridDefinitionModifier($params) {    $params['definition']->getBulkActions()->add(      (new SubmitBulkAction('disable_selection'))      ->setName('Subscribe newsletter')      ->setOptions([        'submit_route' => 'admin_shipit_customers_bulk_subscribe_newsletter',      ])     );`

**Comment by a-suez** [comment]
> Gracias por este aporte! En la versión 1.7.7.3 con el plugin 1.2.3
> 
> `public function hookActionOrderGridDefinitionModifier($params) { $params['definition']->getBulkActions()->add( (new SubmitBulkAction('disable_selection')) ->setName('Subscribe newsletter') ->setOptions([ 'submit_route' => 'admin_shipit_customers_bulk_subscribe_newsletter', ]) );`

Gracias Sergio! ¿Dices que con esa modificación funciona en 1.7.7.3? Si es así, por favor ¿me podrías decir cual es el archivo que hay que modificar con esto?

Saludos

**Comment by sergioaraos** [comment]
> > Gracias por este aporte! En la versión 1.7.7.3 con el plugin 1.2.3
> > `public function hookActionOrderGridDefinitionModifier($params) { $params['definition']->getBulkActions()->add( (new SubmitBulkAction('disable_selection')) ->setName('Subscribe newsletter') ->setOptions([ 'submit_route' => 'admin_shipit_customers_bulk_subscribe_newsletter', ]) );`
> 
> Gracias Sergio! ¿Dices que con esa modificación funciona en 1.7.7.3? Si es así, por favor ¿me podrías decir cual es el archivo que hay que modificar con esto?
> 
> Saludos

No, solo comenté la función y pasa. No tengo claro la relevancia del formulario de suscripción al newsletter. Intentamos injectando el USE, pero luego se cae posteriormente., ya que no hay template para esa ruta. En /modules/rg_shipit/rg_shipit.php, comenta las líneas 1394 a las 1400.

**Comment by sergioaraos** [comment]
1.7.7.4 + PHP 7.3 el error se mantiene.

**Comment by hansscd** [comment]
Alguna actualización sobre el problema ?

**Comment by a-suez** [comment]
Parece haber un WIP ya :)

https://github.com/shipit-team/prestashop/pull/17
